config/routes.rb
MovieRental::Application.routes.draw do
  resources :customers

  resources :movies
  resources :rentals

  root :to => "movies#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :rentals
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates_presence_of :name,:year
  validates_numericality_of :year, :only_integer => true, :greater_than => 1930, :less_than_or_equal_to => Time.now.year
  validates_uniqueness_of :name, :scope => :year
  after_initialize :defaults

  def mark_as_rented
    self.status =  "rented"
    self.save
  end
  
  private
  def defaults
    self.status ||= "available"
  end
end

app/models/rental.rb
class Rental < ActiveRecord::Base

  belongs_to :movie
  belongs_to :customer
  before_save :mark_as_rented

  private
  def mark_as_rented
    if self.movie.status == "available"
      self.movie.mark_as_rented
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to(@customer, :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(@customer, :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params[:movie])
    if @movie.save
      flash[:notice] = "Movie added successfully!"
      redirect_to movie_path(@movie)
    else
      render 'movies/new'
    end
  end

  def index
    @movies = Movie.all
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      flash[:notice] = "Movie deleted successfully!"
      redirect_to movies_path
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(params[:movie])
      flash[:notice] = "Movie upated successfully!"
      redirect_to movies_path
    else
      render 'movies/edit'
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(params[:rental])
    if @rental.save
      flash[:notice] = "#{@rental.movie.name} has been rented to #{@rental.customer.name}!"
      redirect_to movies_path
    else
      flash[:notice] = "Sorry! That movie could not be rented out"
      render 'rentals/new'
    end
  end

  def show
  end

  def update
  end

  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.address %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Rental</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1> All Wood Movie Rentals </h1>
<section id="flash_msg">
  <% flash.each do |key, value| %>
    <%= content_tag(:div,value,:class => "flash #{key}") %>
  <% end %>  
</section>
<%= yield %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <h2> <%= pluralize(@movie.errors.count,"error") %> prevented movie from being saved: </h2>
    <p> There were problems with the following fields: </p>
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li> <%= "#{msg}" %> </li>
    <% end %>
    </ul>
   <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, ["English", "Hindi", "Telugu"], :include_blank => false %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h2>Edit Movie</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h2>Movie Listing</h2>
<table>
<tr>
<th>Movie</th>
<th>Genre</th>
</tr>
<% @movies.each do |movie| %>
  <tr>
  <td> <%= link_to movie.name, movie_path(movie) %> </td>
  <td> <%= movie.genre %> </td>
  <td> <%= link_to "Edit", edit_movie_path(movie) %> </td>
  <td> <%= link_to "Delete", movie_path(movie), :method => "delete", :confirm => "Are you sure?" %> </td>
  </tr>
<% end %>
</table>
<p>
<%= link_to "Add Movie", new_movie_path %>
<%= link_to "Rent a Movie", new_rental_path %>
<%= link_to "Customers", customers_path %>
</p>

app/views/movies/new.html.erb
<h2>Create Movie</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<h2>Movie: <%= @movie.name %> </h2>
<ul>
<li>Release Year: <%= @movie.year %> </li>
<li>Genre: <%= @movie.genre %> </li>
<li>Language: <%= @movie.language %> </li>
</ul>
<p><%= link_to "Movie Listing", movies_path %></p>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <h2> <%= pluralize(@rental.errors.count,"error") %> prevented movie from being saved: </h2>
    <p> There were problems with the following fields: </p>
    <ul>
    <% @rental.errors.full_messages.each do |msg| %>
      <li> <%= "#{msg}" %> </li>
    <% end %>
    </ul>
   <% end %>

  <div class="field">
    <%= f.label :movie_id, "Movie" %><br />
    <%= f.collection_select :movie_id, Movie.all, :id, :name, :prompt=>true %>
  </div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :customer_id, "Customer" %><br />
    <%= f.collection_select :customer_id,Customer.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/rentals/destroy.html.erb
<h1>Rentals#destroy</h1>
<p>Find me in app/views/rentals/destroy.html.erb</p>

app/views/rentals/edit.html.erb
<h1>Rentals#edit</h1>
<p>Find me in app/views/rentals/edit.html.erb</p>

app/views/rentals/new.html.erb
<h2> Rent a Movie </h2>
<%= render 'form' %>

app/views/rentals/show.html.erb
<h1>Rentals#show</h1>
<p>Find me in app/views/rentals/show.html.erb</p>

app/views/rentals/update.html.erb
<h1>Rentals#update</h1>
<p>Find me in app/views/rentals/update.html.erb</p>